version: '3'
services:
  app:
    image: node:14
    working_dir: /app
    volumes:
      - ./app:/app
    command: npm start
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production

